package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"

	"go.yaml.in/yaml/v3"
)

type definition struct {
	Services map[string]service `yaml:"services"`
}

type service struct {
	Operations map[string]operation `yaml:"operations"`
}

type operation struct {
	Input  typeRef `yaml:"input"`
	Output typeRef `yaml:"output"`
}

type typeRef struct {
	GoRef string `yaml:"$goRef"`
}

type preparedService struct {
	Name       string
	Handler    string
	Builder    string
	Operations []preparedOperation
}

type preparedOperation struct {
	Name       string
	Method     string
	Input      string
	Output     string
	StructName string
}

func main() {
	packageName := flag.String("package", "", "generated Go package name")
	outFile := flag.String("out-file", "", "output file")
	flag.Parse()

	if *packageName == "" {
		fatalf("--package is required")
	}
	if *outFile == "" {
		fatalf("--out-file is required")
	}
	if flag.NArg() != 1 {
		fatalf("expected one .nexusrpc.yaml input file")
	}

	data, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fatalf("read input: %v", err)
	}

	var def definition
	if err := yaml.Unmarshal(data, &def); err != nil {
		fatalf("parse input: %v", err)
	}

	services, err := prepare(def)
	if err != nil {
		fatalf("%v", err)
	}

	src, err := render(*packageName, services)
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(*outFile, src, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
	fmt.Printf("Writing %s\n", *outFile)
}

func prepare(def definition) ([]preparedService, error) {
	if len(def.Services) == 0 {
		return nil, fmt.Errorf("no services found")
	}

	serviceNames := sortedKeys(def.Services)
	services := make([]preparedService, 0, len(serviceNames))
	for _, serviceName := range serviceNames {
		svc := def.Services[serviceName]
		if len(svc.Operations) == 0 {
			return nil, fmt.Errorf("service %q has no operations", serviceName)
		}

		opNames := sortedKeys(svc.Operations)
		ops := make([]preparedOperation, 0, len(opNames))
		for _, opName := range opNames {
			op := svc.Operations[opName]
			if op.Input.GoRef == "" {
				return nil, fmt.Errorf("service %q operation %q is missing input $goRef", serviceName, opName)
			}
			if op.Output.GoRef == "" {
				return nil, fmt.Errorf("service %q operation %q is missing output $goRef", serviceName, opName)
			}
			method := pascal(opName)
			ops = append(ops, preparedOperation{
				Name:       opName,
				Method:     method,
				Input:      op.Input.GoRef,
				Output:     op.Output.GoRef,
				StructName: lowerFirst(serviceName) + method + "Operation",
			})
		}

		services = append(services, preparedService{
			Name:       serviceName,
			Handler:    serviceName + "Handler",
			Builder:    "New" + serviceName + "Service",
			Operations: ops,
		})
	}

	return services, nil
}

func render(packageName string, services []preparedService) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by nexus-server-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"context\"\n\n")
	fmt.Fprintf(&b, "\tnexussdk \"github.com/nexus-rpc/sdk-go/nexus\"\n")
	fmt.Fprintf(&b, ")\n")

	for _, svc := range services {
		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "type %s interface {\n", svc.Handler)
		for _, op := range svc.Operations {
			fmt.Fprintf(
				&b,
				"\t%s(ctx context.Context, input %s, options nexussdk.StartOperationOptions) (nexussdk.HandlerStartOperationResult[%s], error)\n",
				op.Method,
				op.Input,
				op.Output,
			)
		}
		fmt.Fprintf(&b, "}\n")

		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "func %s(handler %s) *nexussdk.Service {\n", svc.Builder, svc.Handler)
		fmt.Fprintf(&b, "\tservice := nexussdk.NewService(%s.ServiceName)\n", svc.Name)
		fmt.Fprintf(&b, "\tservice.MustRegister(\n")
		for _, op := range svc.Operations {
			fmt.Fprintf(&b, "\t\t&%s{handler: handler},\n", op.StructName)
		}
		fmt.Fprintf(&b, "\t)\n")
		fmt.Fprintf(&b, "\treturn service\n")
		fmt.Fprintf(&b, "}\n")

		for _, op := range svc.Operations {
			fmt.Fprintf(&b, "\n")
			fmt.Fprintf(&b, "type %s struct {\n", op.StructName)
			fmt.Fprintf(&b, "\tnexussdk.UnimplementedOperation[%s, %s]\n", op.Input, op.Output)
			fmt.Fprintf(&b, "\thandler %s\n", svc.Handler)
			fmt.Fprintf(&b, "}\n")

			fmt.Fprintf(&b, "\n")
			fmt.Fprintf(&b, "func (o *%s) Name() string {\n", op.StructName)
			fmt.Fprintf(&b, "\treturn %s.%s.Name()\n", svc.Name, op.Method)
			fmt.Fprintf(&b, "}\n")

			fmt.Fprintf(&b, "\n")
			fmt.Fprintf(
				&b,
				"func (o *%s) Start(ctx context.Context, input %s, options nexussdk.StartOperationOptions) (nexussdk.HandlerStartOperationResult[%s], error) {\n",
				op.StructName,
				op.Input,
				op.Output,
			)
			fmt.Fprintf(&b, "\treturn o.handler.%s(ctx, input, options)\n", op.Method)
			fmt.Fprintf(&b, "}\n")
		}
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func pascal(s string) string {
	var b strings.Builder
	capNext := true
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' {
			capNext = true
			continue
		}
		if capNext {
			b.WriteRune(unicode.ToUpper(r))
			capNext = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
